package org.xitikit.examples.java.mysql.logwatch.data;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import static javax.persistence.GenerationType.*;

//@formatter:off
/**
 * Represents a single row in the blocked_ipv4 table.
 * SQL Example:
 * <p>
 * CREATE TABLE IF NOT EXISTS blocked_ipv4 (
 *   id     INT AUTO_INCREMENT PRIMARY KEY,
 *   ipv4   VARCHAR(15)  NOT NULL,
 *   reason VARCHAR(512) NOT NULL
 * )
 */
//@formatter:on
@Entity
@Table(name = "blocked_ipv4")
public class BlockedIpv4{

    /**
     * The id as generated and incremented by the database.
     * This value has no relation to any field in the actual
     * entry in the log files; it is simply here to provide
     * identity.
     */
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", insertable = false, nullable = false, unique = true)
    private Integer id;

    /**
     * The ip address, in IPv4 format, contained in the second column of the logs entry.
     */
    @NotNull
    @Size(max = 15)
    @Pattern(
        regexp = "(([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\.){3}([01]?\\d\\d?|2[0-4]\\d|25[0-5])",
        message = "Only IPv4 Addresses Supported")
    @Column(name = "ipv4", length = 15, updatable = false, nullable = false)
    private String ipv4;

    /**
     * The text which indicates the reason for blocking the IP
     */
    @NotNull
    @Size(max = 512)
    @Column(name = "reason", updatable = false, nullable = false)
    private String reason;

    /**
     * Defaults all values to null.
     * With the exception of the 'id', all fields
     * will need a NonNull value before being persisted.
     */
    public BlockedIpv4(){

    }

    /**
     * An almost-all-arg constructor with WYSIWYG behaviour.
     * Since the id should be generated by the database, it is omitted here.
     */
    public BlockedIpv4(final String ipv4, final String reason){

        this.ipv4 = ipv4;
        this.reason = reason;
    }

    public Integer getId(){

        return id;
    }

    public void setId(final Integer id){

        this.id = id;
    }

    public String getIpv4(){

        return ipv4;
    }

    public void setIpv4(final String ipv4){

        this.ipv4 = ipv4;
    }

    public String getReason(){

        return reason;
    }

    public void setReason(final String reason){

        this.reason = reason;
    }
}
