spring:
  application:
    name: log-watch-cli
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/logwatch_db?useSSL=false
    user: logwatch_user
    password: ChangeThisInYourSettingsXmlAndApplicationProperties
    init-sqls: SELECT 1
    encoding: UTF-8
    clean-disabled: true
  datasource:
    username: logwatch_user
    password: "ChangeThisInYourSettingsXmlAndApplicationProperties"
    url: jdbc:mysql://localhost:3306/logwatch_db?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: logwatch_pool
      username: logwatch_user
      password: "ChangeThisInYourSettingsXmlAndApplicationProperties"
      jdbc-url: jdbc:mysql://localhost:3306/logwatch_db?useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum-idle: 2
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      connection-init-sql: SELECT 1