package org.xitikit.examples.java.mysql.logwatch.data;

import javax.persistence.*;
import javax.validation.constraints.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import static javax.persistence.GenerationType.*;

//@formatter:off
/**
 * Represents a single row in the LOG_ENTRY table.
 * SQL Example:
 * <p>
 * CREATE TABLE IF NOT EXISTS LOG_ENTRY (
 *   ID         INT AUTO_INCREMENT PRIMARY KEY,
 *   DATE       TIMESTAMP    NOT NULL,
 *   IPV4       VARCHAR(15)  NOT NULL,
 *   REQUEST    VARCHAR(20)  NOT NULL,
 *   STATUS     INT          NOT NULL,
 *   USER_AGENT VARCHAR(256) NOT NULL
 * )
 *
 */
//@formatter:on
@Entity
@Table(name = "log_entry")
public class LogEntry{

    /**
     * The id as generated and incremented by the database.
     * This value has no relation to any field in the actual
     * entry in the log files; it is simply here to provide
     * identity.
     */
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", insertable = false, nullable = false, unique = true)
    private Integer id;

    /**
     * This is the first 'column' in the logs row entry.
     * Maps to a TIMESTAMP type in the database.
     */
    @NotNull
    @Convert(converter = LocalDateTimeConverter.class)
    @Column(name = "date", updatable = false, nullable = false)
    private LocalDateTime date;

    /**
     * The ip address, in IPv4 format, contained in the second column of the logs entry.
     */
    @NotNull
    @Size(max = 15)
    @Pattern(
        // Forgive me Father, for I have sinned
        // Regex knowledge bad
        // Used google and it works
        regexp = "(([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\.){3}([01]?\\d\\d?|2[0-4]\\d|25[0-5])",
        message = "Only IPv4 Addresses Supported")
    @Column(name = "ipv4", length = 15, updatable = false, nullable = false)
    private String ipv4;

    /**
     * This should contain the request information, such as type and HTTP protocol.
     * The values are in the second column of the log entry
     */
    @Column(name = "request", length = 20, updatable = false, nullable = false)
    @NotNull
    @Size(max = 20)
    private String request;

    /**
     * The HTTP Status code, with a value from 100 and less than 600.
     */
    @NotNull
    @Min(value = 100, message = "HTTP Status values must have a minimum value of 100")
    @Max(value = 599, message = "HTTP Status values must have a maximum value of 599")
    @Column(name = "status", updatable = false, nullable = false)
    private Integer status;

    /**
     * The text which indicates the browser that was used to access the application.
     */
    @NotNull
    @Size(max = 256)
    @Column(name = "user_agent", updatable = false, nullable = false)
    private String userAgent;

    /**
     * Defaults all values to null.
     * With the exception of the 'id', all fields
     * will need a NonNull value before being persisted.
     */
    public LogEntry(){

    }

    /**
     * An almost-all-arg constructor with WYSIWYG behaviour.
     * Since the id should be generated by the database, it is omitted here.
     */
    public LogEntry(final LocalDateTime date, final String ipv4, final String request, final Integer status, final String userAgent){

        this.date = date;
        this.ipv4 = ipv4;
        this.request = request;
        this.status = status;
        this.userAgent = userAgent;
    }

    public Integer getId(){

        return id;
    }

    public void setId(final Integer id){

        this.id = id;
    }

    public LocalDateTime getDate(){

        return date;
    }

    public void setDate(final LocalDateTime date){

        this.date = date;
    }

    public String getIpv4(){

        return ipv4;
    }

    public void setIpv4(final String ipv4){

        this.ipv4 = ipv4;
    }

    public String getRequest(){

        return request;
    }

    public void setRequest(final String request){

        this.request = request;
    }

    public Integer getStatus(){

        return status;
    }

    public void setStatus(final Integer status){

        this.status = status;
    }

    public String getUserAgent(){

        return userAgent;
    }

    public void setUserAgent(final String userAgent){

        this.userAgent = userAgent;
    }

    @Override
    public String toString(){

        return DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss.SSS").format(date) + "|" +
            ipv4 + "|" +
            request + "|" +
            status  + "|" +
            userAgent  + "|";
    }
}
